### ISSUE TITLE
Problems charging the collection

### ISSUE THREAD

**Issue by deneb78it** [k3rn3l-p4n1c/postpython#3]
I installed the library as explained and I've found two issues.

1 - I used a Python 2.7 Interpreter and, starting the same lines in the example, Python issiues the following error:
C:\Python27\python.exe C:/SVN/pe_ami_lm_test/Trunk/tests/CMS_3.0/Postman/PO-Authentication.py
Traceback (most recent call last):
  File "C:/SVN/pe_ami_lm_test/Trunk/tests/CMS_3.0/Postman/PO-Authentication.py", line 10, in <module>
    runner = PostPython("C:/SVN/pe_ami_lm_test/Trunk/tests/CMS_3.0/Postman/path/Postman Echo.postman_collection.json")
  File "C:\Python27\lib\site-packages\postpython\core.py", line 25, in __init__
    with open(postman_collection_file_path, encoding='utf8') as postman_collection_file:
TypeError: 'encoding' is an invalid keyword argument for this function

Process finished with exit code 1

2 - I switched to Python 3 interpreter and started the same script- This time the error is:

Traceback (most recent call last):
  File "C:/SVN/pe_ami_lm_test/Trunk/tests/CMS_3.0/Postman/PO-Authentication.py", line 10, in <module>
    runner = PostPython("C:/SVN/pe_ami_lm_test/Trunk/tests/CMS_3.0/Postman/path/Postman Echo.postman_collection.json")
  File "C:\Users\msanto\AppData\Local\Programs\Python\Python37-32\lib\site-packages\postpython\core.py", line 31, in __init__
    self.__load()
  File "C:\Users\msanto\AppData\Local\Programs\Python\Python37-32\lib\site-packages\postpython\core.py", line 35, in __load
    for req in self.__postman_collection['requests']:
KeyError: 'requests'

The library is taken from Postman Webpage
Here the script:

from postpython.core import PostPython

runner = PostPython("C:/SVN/pe_ami_lm_test/Trunk/tests/CMS_3.0/Postman/path/Postman Echo.postman_collection.json")

response = runner.Token.post()
print(response.json())
print(response.status_code)

**Comment by bardia-heydari** [comment]
This error happened because of postpython only support postman v1, currently. You can follow #6 for further news about v2.1 support
