### ISSUE TITLE
Requests not available 

### ISSUE THREAD

**Issue by sayr777** [k3rn3l-p4n1c/postpython#7]
I run
```
from postpython.core import PostPython
runner = PostPython('test1.json')
runner.RequestMethods.help()
```
response
```
Traceback (most recent call last):
  File "C:\Python\Python36-32\lib\site-packages\IPython\core\interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-18-76c0bbfcceaf>", line 1, in <module>
    runner.RequestMethods.help()
  File "C:\Python\Python36-32\lib\site-packages\postpython\core.py", line 52, in __getattr__
    similar = difflib.get_close_matches(item, self.__folders)[0]
IndexError: list index out of range
```

**Comment by bardia-heydari** [comment]
@sayr777, Would you please send me `test1.json` as well?

**Comment by NaveenKumar-G** [comment]
i run with V1 but still giving same error

from postpython.core import PostPython
runner = PostPython('/Users/naveen.gedela/Desktop/Demo_APi.postman_collection.json')
response = runner.DemoApi.get_request()
print(response.json())

/usr/local/bin/python3.6 /Users/naveen.gedela/IdeaProjects/PostPython/Test.py
Traceback (most recent call last):
  File "/Users/naveen.gedela/IdeaProjects/PostPython/Test.py", line 4, in <module>
    response = runner.DemoApi.get_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/postpython/core.py", line 53, in __getattr__
    similar = difflib.get_close_matches(item, self.__folders)[0]
IndexError: list index out of range

It's Json file but when i do upload it's not supporting by github changed to Docx
[Demo_APi.postman_collection.docx](https://github.com/k3rn3l-p4n1c/postpython/files/5647185/Demo_APi.postman_collection.docx)


It's Folder of my collection
![Screenshot 2020-12-05 at 7 18 58 PM](https://user-images.githubusercontent.com/52496278/101244847-bf279e00-372e-11eb-819c-b984d0222674.png)
